# Generated by Django 2.0.1 on 2018-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180110_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
