# Generated by Django 2.0.1 on 2018-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180116_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.IntegerField(choices=[(0, 'Uncategorized'), (1, 'Data Analysis'), (2, 'Web Development')], default=0),
        ),
    ]
