# Generated by Django 2.0 on 2018-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180119_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
