# Generated by Django 2.0 on 2018-02-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_demo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_tag',
            field=models.CharField(blank=True, help_text='put the name tag for demo_url', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.IntegerField(choices=[(0, 'Uncategorized'), (1, 'Data Analysis'), (2, 'Database Management')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_name',
            field=models.CharField(blank=True, help_text='put the name for demo_url', max_length=100),
        ),
    ]
