# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: linli-ding:us-east1:projects-instance

runtime_config:
  python_version: 3

# libraries:
# - name: PIL
#   version: "1.1.7"
  
# [END runtime]

